_wandb:
    value:
        cli_version: 0.26.1
        e:
            pi7zbmuu9gqpok5ndgdm3acom1gm3pbj:
                args:
                    - nyc_airbnb/clean_sample.csv:latest
                    - "0.2"
                    - --random_seed
                    - "42"
                    - --stratify_by
                    - neighbourhood_group
                codePath: components/train_val_test_split/run.py
                codePathLocal: components/train_val_test_split/run.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "2160158191616"
                        used: "625443713024"
                executable: /workspace/Project-Build-an-ML-Pipeline-Starter/venv/bin/python
                git:
                    commit: 4bfb05b6ee52f454021084453e269de66e9fb5fa
                    remote: https://github.com/silver1475/Project-Build-an-ML-Pipeline-Starter.git
                host: 8e67ba7f14e90f7b283e7a713501e1f1b980ccf3-c9b9445fb-dphpf
                memory:
                    total: "135077654528"
                os: Linux-6.6.97+-x86_64-with-glibc2.31
                program: /workspace/Project-Build-an-ML-Pipeline-Starter/components/train_val_test_split/run.py
                python: CPython 3.10.13
                root: /workspace/Project-Build-an-ML-Pipeline-Starter
                startedAt: "2026-05-08T02:11:39.793378Z"
                writerId: pi7zbmuu9gqpok5ndgdm3acom1gm3pbj
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.10.13
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
input:
    value: nyc_airbnb/clean_sample.csv:latest
random_seed:
    value: 42
stratify_by:
    value: neighbourhood_group
test_size:
    value: 0.2
