main:
  project_name: nyc_airbnb
  experiment_name: development
  steps: "download,basic_cleaning,data_split,train_random_forest"

data:
  # Using the full URL for the sample2 release test
  file_url: "sample2.csv"

etl:
  min_price: 10
  max_price: 350

modeling:
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  stratify_by: neighbourhood_group
  max_tfidf_features: 10